default:
  image: ghcr.io/foamscience/jammy-openfoam:v2012

stages: # If things don't compile, there is no need to carry on
  - build
  - test

build-job:
  stage: build
  tags:
    - local
    - v2012
  script: 
    - echo "Compiling the libs..."
    - source /usr/lib/openfoam/openfoam2012/etc/bashrc && mkdir -p /home/openfoam/OpenFOAM/openfoam-v2012/platforms/linux64GccDPInt32Opt/lib && ./Allwmake
    - echo "Done."

unit-test-job:
  stage: test
  tags:
    - local
    - v2012
  script:
    - echo "Running unit tests... "
    - cd tests
    - git clone https://github.com/FoamScience/foamUT
    - export AMR_PROJECT=$CI_PROJECT_DIR
    - export CATCH_TIMEOUT=180
    - rm -rf foamUT/tests/exampleTests
    - ln -s $CI_PROJECT_DIR/tests/adaptiveFvMeshTests $CI_PROJECT_DIR/tests/foamUT/tests/adaptiveFvMeshTests
    - cp -r testCases foamUT/cases
    - cd foamUT
    - source /usr/lib/openfoam/openfoam2012/etc/bashrc
    - ./Alltest
